"""The Python half of the Swift/Python contract.

``ios/Packages/RFMapper/Tests/RFMapperCoreTests/ContractFixtureTests.swift`` writes
``RFMapper_OBSI1_2026-05-04.zip`` into ``contract/`` from the Swift export engine. This reads it
back.

That direction is the valuable one. The Swift tests can only check Swift against its own
expectations; this checks it against a second, independent implementation. ``read_package``
recomputes every ``row_checksum`` and every ``checksum.txt`` digest from scratch and cross-checks the
CSV view against the JSON view, so a package that arrives here with no issues has demonstrated that
Swift's CSV dialect, decimal formatting, metadata ordering, SHA-256 and archive layout all match the
Kotlin producer's — not merely that they are self-consistent.

The fixture is committed, so this runs without a Swift toolchain.
"""

from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import pytest

from rfmapper_lab.fusion.windows import build_vectors, carries_evidence
from rfmapper_lab.models import PrecisionTier, SensorType
from rfmapper_lab.params import DEFAULTS
from rfmapper_lab.parsing.dataset import Dataset, IngestStats
from rfmapper_lab.parsing.package_reader import read_package
from rfmapper_lab.parsing.reference_reader import parse_reference_model
from rfmapper_lab.pipeline import PipelineConfig, run_pipeline

PACKAGE = "RFMapper_OBSI1_2026-05-04.zip"

# The iPhone's own identity. An association observation says "*this observer* is attached to that
# access point", so it is evidence about a device only once the administrator has enrolled the phone
# as a managed device. That enrollment is the deployment requirement recorded in
# ``docs/20-ios-collector.md`` §4, and it is REFERENCE data rather than something the Lab may infer.
IOS_DEVICE_ID = "DEVICE-IPHONE-1"
IOS_OBSERVER_ID = "OBS-I1"


@pytest.fixture(scope="module")
def contract_dir() -> Path:
    directory = Path(__file__).resolve().parents[2] / "contract"
    if not (directory / PACKAGE).exists():
        pytest.skip(
            f"{PACKAGE} is absent. Generate it with: "
            "cd ios && RFMAPPER_WRITE_CONTRACT=1 swift test --filter ContractFixtureTests"
        )
    return directory


@pytest.fixture(scope="module")
def ios_package(contract_dir: Path):
    return read_package(contract_dir / PACKAGE)


@pytest.fixture(scope="module")
def model_with_ios_device(contract_dir: Path):
    """The shared site model, plus the enrolled iPhone.

    The overlay lives here rather than in ``contract/site_model.json`` because that file is a golden
    fixture generated by the Kotlin side; editing it by hand would break the Kotlin test that
    asserts its bytes. What matters for this test is the enrollment rule, not where it is authored.
    """
    site = json.loads((contract_dir / "site_model.json").read_text())
    registry = json.loads((contract_dir / "devices.json").read_text())

    registry["managed_devices"] = [
        *registry["managed_devices"],
        {
            "device_id": IOS_DEVICE_ID,
            "friendly_name": "Survey iPhone",
            "device_type": "PHONE",
            "status": "AUTHORIZED",
            "known_wifi_identifiers": [],
            "known_ble_identifiers": [],
            "known_service_uuids": [],
            "identifiers": [IOS_OBSERVER_ID],
        },
    ]
    return parse_reference_model(site | registry)


class TestTheSwiftPackageIsReadable:
    def test_a_swift_written_package_validates_with_no_issues(self, ios_package) -> None:
        # Every issue this could report is a disagreement between the two implementations: a row
        # checksum computed differently, an entry digest over different bytes, a CSV row that does
        # not match its JSON twin, a manifest whose counts do not match its contents.
        assert [issue.problem.value for issue in ios_package.issues] == []
        assert len(ios_package.observations) == 15

    def test_the_observer_declares_what_ios_cannot_do(self, ios_package) -> None:
        observer = ios_package.observer
        assert observer is not None

        # The load-bearing half of an iOS observer's identity. Without `unsupported`, the Lab would
        # read an iOS observer's total absence of Wi-Fi scan results as "no access points were
        # present here" and drive every fingerprint's Wi-Fi visibility probability toward zero.
        assert set(observer["capabilities"]) == {"BLE", "GPS", "WIFI_ASSOCIATION"}
        assert set(observer["unsupported"]) == {"WIFI_SCAN", "RTT"}
        assert observer["platform"] == "ios"

    def test_ios_ble_identifiers_are_marked_as_app_install_scoped(self, ios_package) -> None:
        ble = [o for o in ios_package.observations if o.sensor_type is SensorType.BLE]
        assert ble

        for observation in ble:
            # CoreBluetooth never discloses a hardware address. Every BLE identifier from an iPhone
            # is an app-install-scoped UUID, and the scope tag is what stops a consumer joining it
            # to another observer's sighting of something else entirely.
            assert observation.metadata["identifier_scope"] == "APP_INSTALL"
            assert observation.identifier_type.name == "OTHER"

    def test_the_awkward_ssid_survived_the_csv_round_trip(self, ios_package) -> None:
        # A comma and a quote in one SSID: legal, and the most likely thing to break a CSV writer.
        # `read_package` cross-checks the CSV against the JSON, so reaching here with no issues
        # already proves both views agree; this states what the value should be.
        ssids = {o.ssid for o in ios_package.observations if o.ssid}
        assert 'Guest, "Public"' in ssids


class TestAssociationWithoutSignalStrength:
    """iOS exposes the BSSID of the network it is joined to, but not that network's RSSI.

    This is not a corner case: it is *every* Wi-Fi row an iOS Collector can produce
    (``docs/06-ios-capability-matrix.md`` §1). The Lab used to require a signal level or a range
    before a row reached a fusion window, so all of them were discarded in silence — an iPhone
    reporting which tower it was attached to yielded no estimate and no diagnostic. On an
    association-based site that is the whole signal.
    """

    def test_every_ios_association_row_arrives_without_an_rssi(self, ios_package) -> None:
        associations = [
            o for o in ios_package.observations if o.sensor_type is SensorType.WIFI_ASSOCIATION
        ]
        assert len(associations) == 5
        assert all(o.rssi is None for o in associations)
        assert all(o.rtt_distance_mm is None for o in associations)
        # And they say why, rather than leaving the gap unexplained.
        degraded = [o for o in associations if o.metadata.get("permission_degraded") == "true"]
        assert degraded
        assert all(
            o.metadata["missing_permissions"] == "WIFI_RSSI_UNAVAILABLE_ON_IOS" for o in degraded
        )

    def test_an_association_is_evidence_even_with_no_signal_level(self, ios_package) -> None:
        associations = [
            o for o in ios_package.observations if o.sensor_type is SensorType.WIFI_ASSOCIATION
        ]
        # A station is associated with exactly one access point, and only within its range. The
        # attachment is itself a proximity statement.
        assert all(carries_evidence(o) for o in associations)

    def test_a_scan_result_with_no_signal_level_is_still_contentless(self, ios_package) -> None:
        # The fix is narrow on purpose. A WIFI_SCAN or BLE row with no RSSI records that something
        # was detected without recording how strongly, which positions nothing.
        ble = next(o for o in ios_package.observations if o.sensor_type is SensorType.BLE)
        assert carries_evidence(ble)
        assert not carries_evidence(replace(ble, rssi=None))

    def test_the_enrolled_iphone_gets_zone_evidence_from_its_own_association(
        self, ios_package, model_with_ios_device
    ) -> None:
        vectors = build_vectors(ios_package.observations, model_with_ios_device, DEFAULTS)
        own = [v for v in vectors if v.device_id == IOS_DEVICE_ID]

        assert own, "the enrolled iPhone's own association produced no live vector"
        associated = [
            m
            for v in own
            for m in v.measurements
            if m.sensor_type is SensorType.WIFI_ASSOCIATION
        ]
        assert associated, "the association measurements were dropped from the window"
        assert all(m.rssi_normalized is None for m in associated)
        # `AP-NORTH` from the shared site model, plus one access point the site model has never
        # heard of -- which is realistic, and handled below.
        assert {m.radio_identifier for m in associated} == {
            "aa:bb:cc:00:00:01",
            "bb:cc:dd:00:00:09",
        }

    def test_an_association_yields_a_zone_and_deliberately_no_coordinates(
        self, ios_package, model_with_ios_device
    ) -> None:
        dataset = Dataset(
            observations=ios_package.observations,
            reference=model_with_ios_device,
            source_dataset_ids=(ios_package.dataset_id,),
            stats=IngestStats(),
        )
        # `zone_anchor_v1` is the classifier for a site whose only fixed reference is infrastructure
        # visibility, which is exactly what an association gives.
        result = run_pipeline(dataset, PipelineConfig(zone_engine="zone_anchor_v1"))
        own = [e for e in result.estimates if e.device_id == IOS_DEVICE_ID]
        assert own, "the enrolled iPhone got no estimate from its own association"

        zoned = [e for e in own if e.precision_tier is PrecisionTier.ZONE]
        assert zoned, "an association to a located access point produced no zone"

        for estimate in zoned:
            # `AP-NORTH` sits in B1-NORTH, and that is the whole of what can be concluded.
            assert estimate.zone_id == "B1-NORTH"
            # Keeping the row must not manufacture precision. There is no survey here, so nothing
            # matches a fingerprint and the strategy order falls through to the zone-only engine.
            assert estimate.method == "pos_zone_only_v1"
            assert estimate.x is None
            assert estimate.y is None
            assert estimate.horizontal_uncertainty_m is None

    def test_an_association_to_an_unregistered_access_point_claims_only_presence(
        self, ios_package, model_with_ios_device
    ) -> None:
        dataset = Dataset(
            observations=ios_package.observations,
            reference=model_with_ios_device,
            source_dataset_ids=(ios_package.dataset_id,),
            stats=IngestStats(),
        )
        result = run_pipeline(dataset, PipelineConfig(zone_engine="zone_anchor_v1"))

        # One row associates to an access point the site model has never heard of. Knowing a device
        # is attached to an unknown AP says it is somewhere on site and nothing more, and the
        # estimate has to stop there rather than borrow a zone from a neighbouring sample.
        presence = [
            e
            for e in result.estimates
            if e.device_id == IOS_DEVICE_ID and e.precision_tier is PrecisionTier.SITE_PRESENCE
        ]
        assert len(presence) == 1
        assert presence[0].zone_id is None
        assert "NO_ZONE_EVIDENCE" in presence[0].quality_flags
